# Travis Continuous Integration Configuration File For ROS Control Projects
language: generic
services:
  - docker

notifications:
  email:
    recipients:
      - bence.magyar.robotics@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

env:
  global:
    - UPSTREAM_WORKSPACE='https://raw.github.com/ros-controls/ros_control/$ROS_DISTRO-devel/ros_control.rosinstall -realtime_tools'
  matrix:
    - ROS_DISTRO=melodic ROS_REPO=ros
    - ROS_DISTRO=melodic ROS_REPO=ros-testing

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci -b master
script:
- .industrial_ci/travis.sh
