name: ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  abi_check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [humble, iron, jazzy, rolling]
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
          ROS_REPO: main
          ABICHECK_URL: github:${{ github.repository }}#${{ github.base_ref }}
          NOT_TEST_BUILD: true
