name: Kilted rosdoc2

on:
  workflow_dispatch:
  pull_request:
    branches:
      - kilted
    paths:
      - doc/**
      - rosdoc2.yaml
      - package.xml

concurrency:
  # cancel previous runs of the same workflow, except for pushes on given branches
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/heads') }}

jobs:
  check:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-rosdoc2.yml@master
